zurg: v1

token: 
port: 59999
network_buffer_size: 1048576
concurrent_workers: 200
check_for_changes_every_secs: 15
enable_repair: true
serve_from_rclone: false
retain_folder_name_extension: false
on_library_update: |
  for arg in "$@"
    do
      echo "detected update on: $arg"
    done
directories:
  torrents:
    group: 1
    filters:
      - regex: /.*/